# Generated by Django 2.2 on 2021-07-06 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=30, verbose_name='型号')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='厂家')),
                ('parameter', models.CharField(max_length=200, verbose_name='主要参数')),
                ('price', models.IntegerField(default=0, verbose_name='售价')),
                ('cost', models.IntegerField(default=0, verbose_name='成本')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('image', models.ImageField(upload_to='products/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '产品管理',
                'verbose_name_plural': '产品管理',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
            },
        ),
    ]
