# Generated by Django 2.2 on 2021-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='num',
            field=models.CharField(default='Product_List_20210708220443', max_length=30, verbose_name='编号'),
        ),
    ]
