# Generated by Django 2.2 on 2021-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210708_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='num',
            field=models.CharField(default='Product_List_20210709152945', max_length=30, verbose_name='编号'),
        ),
    ]
