# Generated by Django 2.2 on 2021-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210709_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='num',
            field=models.CharField(default='Product_List_20210709165807', max_length=30, verbose_name='编号'),
        ),
    ]
