# Generated by Django 2.2 on 2021-07-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Company', verbose_name='购买方'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品配置'),
        ),
    ]
