# Generated by Django 2.2 on 2021-07-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210708_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperson',
            name='position',
            field=models.CharField(default='未知', max_length=50, verbose_name='哪里人'),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='age',
            field=models.IntegerField(blank=True, default=18, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='come_from',
            field=models.CharField(blank=True, max_length=50, verbose_name='哪里人'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='image',
            field=models.ImageField(blank=True, upload_to='customers/%Y/%m', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('wbb', '未报备'), ('bbz', '报备中'), ('ybb', '已报备'), ('bbcq', '报备超期'), ('bbsb', '报备失败'), ('ycj', '已成交')], default='wbb', max_length=4, verbose_name='状态'),
        ),
    ]
