# Generated by Django 2.2 on 2021-07-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210708_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperson',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Company', verbose_name='就职公司'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='position',
            field=models.CharField(default='未知', max_length=50, verbose_name='职位'),
        ),
    ]
