# Generated by Django 2.2 on 2021-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210708_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('baidu', '百度'), ('douyin', '抖音'), ('synology', '群晖厂家'), ('shiwei', '世伟总代'), ('jieshao', '介绍'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='项目来源'),
        ),
    ]
